"""
main.py — BookRAG FastAPI Application

Exposes the RAG pipeline over HTTP via two endpoints:

    GET  /health  — liveness + readiness check
    POST /ask     — submit a question, receive an answer from the RAG pipeline

Industry-standard features included:
    - Request ID (UUID) injected per request; returned in body + response headers
    - Structured logging: every request/response is logged with method, path,
      status code, latency, and request_id
    - X-Request-ID and X-Process-Time-Ms response headers on every response
    - CORS middleware (configurable origins)
    - Pydantic request/response models with field-level validation
    - Custom exception handlers for ValueError (422) and RuntimeError (500)
    - Lifespan context manager: RAGPipeline is constructed ONCE at startup
      (loads FAISS index, embedding model, API clients) and reused across calls
    - /docs and /redoc auto-generated by FastAPI (OpenAPI spec)

Run:
    From the project root:
        uv run uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload

    Or via the __main__ block:
        uv run python src/api/main.py
"""

import logging
import sys
import time
import uuid
from contextlib import asynccontextmanager
from pathlib import Path
from typing import AsyncGenerator

import uvicorn
from fastapi import FastAPI, HTTPException, Request, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field, field_validator

# ── Path setup ────────────────────────────────────────────────
# main.py is at: BookRAGProject/src/api/main.py
#   parents[0] = src/api/
#   parents[1] = src/
#   parents[2] = BookRAGProject/  ← project root (config/ lives here)
_PROJECT_ROOT    = Path(__file__).resolve().parents[2]
_RAG_PIPELINE_DIR = _PROJECT_ROOT / "src" / "app" / "rag_pipeline"

sys.path.insert(0, str(_PROJECT_ROOT))
sys.path.insert(0, str(_RAG_PIPELINE_DIR))

from config.config import API_HOST, API_PORT
from rag_pipeline_orc import RAGPipeline

# ──────────────────────────────────────────────
# Logging
# ──────────────────────────────────────────────

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
)
logger = logging.getLogger("bookrag.api")


# ──────────────────────────────────────────────
# Pipeline singleton
# ──────────────────────────────────────────────

_pipeline: RAGPipeline | None = None


# ──────────────────────────────────────────────
# Lifespan (startup / shutdown)
# ──────────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncGenerator[None, None]:
    """
    FastAPI lifespan context manager.

    On startup : initialise the RAGPipeline once (loads FAISS index,
                 embedding model, Groq client, Cohere client, LangSmith).
    On shutdown: log a graceful shutdown message.

    Keeping the pipeline as a module-level singleton means all expensive
    resources are loaded exactly once per process, not per request.
    """
    global _pipeline
    logger.info("Startup — loading RAG pipeline (FAISS, embeddings, API clients)...")
    try:
        _pipeline = RAGPipeline()
        logger.info("RAG pipeline loaded successfully. Server is ready.")
    except Exception as e:
        logger.error(f"Failed to load RAG pipeline: {e}")
        raise

    yield  # server is live here

    logger.info("Shutdown — releasing resources.")
    _pipeline = None


# ──────────────────────────────────────────────
# App
# ──────────────────────────────────────────────

app = FastAPI(
    title="BookRAG API",
    description=(
        "Retrieval-Augmented Generation API. "
        "Ask questions about the book knowledge base and receive grounded answers."
    ),
    version="1.0.0",
    lifespan=lifespan,
    docs_url="/docs",
    redoc_url="/redoc",
)


# ──────────────────────────────────────────────
# Middleware
# ──────────────────────────────────────────────

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],        # tighten in production (list specific origins)
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


@app.middleware("http")
async def request_logging_middleware(request: Request, call_next):
    """
    Per-request middleware that:
        1. Generates a UUID request_id and attaches it to request.state.
        2. Logs the incoming request (method, path, request_id).
        3. Calls the next handler and measures wall-clock latency.
        4. Injects X-Request-ID and X-Process-Time-Ms into the response headers.
        5. Logs the outgoing response (status code, latency, request_id).
    """
    request_id = str(uuid.uuid4())
    request.state.request_id = request_id

    logger.info(
        f"→ {request.method} {request.url.path} | "
        f"client={request.client.host if request.client else 'unknown'} | "
        f"request_id={request_id}"
    )

    start = time.perf_counter()
    response = await call_next(request)
    elapsed_ms = (time.perf_counter() - start) * 1000

    response.headers["X-Request-ID"]       = request_id
    response.headers["X-Process-Time-Ms"]  = f"{elapsed_ms:.2f}"

    logger.info(
        f"← {request.method} {request.url.path} | "
        f"status={response.status_code} | {elapsed_ms:.2f}ms | "
        f"request_id={request_id}"
    )

    return response


# ──────────────────────────────────────────────
# Pydantic Models
# ──────────────────────────────────────────────

class AskRequest(BaseModel):
    """
    Request body for POST /ask.

    Attributes:
        query (str): The user's question. Must be 3–500 characters and non-blank.
    """
    query: str = Field(
        ...,
        min_length=3,
        max_length=500,
        description="The question to ask the RAG pipeline.",
        examples=["What is the attention mechanism in transformers?"],
    )

    @field_validator("query")
    @classmethod
    def query_must_not_be_blank(cls, v: str) -> str:
        """Strip and reject blank/whitespace-only queries."""
        stripped = v.strip()
        if not stripped:
            raise ValueError("query must not be blank or whitespace-only.")
        return stripped


class AskResponse(BaseModel):
    """
    Successful response body for POST /ask.

    Attributes:
        request_id (str):  UUID that uniquely identifies this request.
        query (str):       The original query (after whitespace normalization).
        answer (str):      LLM-generated answer grounded in the retrieved context.
        latency_ms (float):Total API handler latency in milliseconds.
    """
    request_id: str
    query:      str
    answer:     str
    latency_ms: float


class HealthResponse(BaseModel):
    """
    Response body for GET /health.

    Attributes:
        status (str):          "ok" when the server is running.
        pipeline_ready (bool): True once the RAGPipeline has been initialised.
        version (str):         API version string.
    """
    status:         str
    pipeline_ready: bool
    version:        str


class ErrorResponse(BaseModel):
    """
    Standardised error body returned for 4xx / 5xx responses.

    Attributes:
        request_id (str):    UUID of the failed request.
        error (str):         Short error category (e.g. "Validation error").
        detail (str | None): Human-readable explanation of the error.
    """
    request_id: str
    error:      str
    detail:     str | None = None


# ──────────────────────────────────────────────
# Exception Handlers
# ──────────────────────────────────────────────

@app.exception_handler(ValueError)
async def value_error_handler(request: Request, exc: ValueError) -> JSONResponse:
    """Handle validation / bad-input errors with HTTP 422."""
    request_id = getattr(request.state, "request_id", str(uuid.uuid4()))
    logger.warning(
        f"Validation error | request_id={request_id} | detail={exc}"
    )
    return JSONResponse(
        status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
        content=ErrorResponse(
            request_id=request_id,
            error="Validation error",
            detail=str(exc),
        ).model_dump(),
    )


@app.exception_handler(RuntimeError)
async def runtime_error_handler(request: Request, exc: RuntimeError) -> JSONResponse:
    """Handle unexpected pipeline failures with HTTP 500."""
    request_id = getattr(request.state, "request_id", str(uuid.uuid4()))
    logger.error(
        f"Pipeline error | request_id={request_id} | detail={exc}",
        exc_info=True,
    )
    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content=ErrorResponse(
            request_id=request_id,
            error="Pipeline error",
            detail=str(exc),
        ).model_dump(),
    )


# ──────────────────────────────────────────────
# Endpoints
# ──────────────────────────────────────────────

@app.get(
    "/health",
    response_model=HealthResponse,
    tags=["Health"],
    summary="Liveness and readiness check",
)
async def health() -> HealthResponse:
    """
    Returns HTTP 200 with pipeline readiness status.

    Use this endpoint for:
        - Load balancer health checks
        - Kubernetes liveness / readiness probes
        - Smoke-testing that the server started correctly
    """
    return HealthResponse(
        status="ok",
        pipeline_ready=_pipeline is not None,
        version="1.0.0",
    )


@app.post(
    "/ask",
    response_model=AskResponse,
    tags=["RAG"],
    summary="Ask a question to the RAG pipeline",
    responses={
        200: {"description": "Answer successfully generated"},
        422: {"model": ErrorResponse, "description": "Invalid query"},
        500: {"model": ErrorResponse, "description": "Pipeline error"},
        503: {"description": "Pipeline not yet ready"},
    },
)
async def ask(body: AskRequest, request: Request) -> AskResponse:
    """
    Submit a natural language question and receive a grounded answer.

    The request is processed through the full RAG pipeline:
        1. Query understanding (clean + rewrite)
        2. FAISS retrieval (top-k candidate chunks)
        3. Cohere reranking (top-n most relevant chunks)
        4. Context building (dedup, token budget, format)
        5. LLM answer generation (Groq / llama-3.3-70b)

    The response includes the answer and the total handler latency.
    LangSmith traces are recorded automatically if configured.
    """
    request_id = getattr(request.state, "request_id", str(uuid.uuid4()))

    if _pipeline is None:
        logger.error(f"Pipeline not ready | request_id={request_id}")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="RAG pipeline is not ready. Please try again shortly.",
        )

    logger.info(
        f"Processing query | request_id={request_id} | "
        f"query='{body.query[:80]}{'...' if len(body.query) > 80 else ''}'"
    )

    start = time.perf_counter()
    answer = _pipeline.run(body.query)
    latency_ms = (time.perf_counter() - start) * 1000

    logger.info(
        f"Query answered | request_id={request_id} | "
        f"answer_len={len(answer)} chars | {latency_ms:.2f}ms"
    )

    return AskResponse(
        request_id=request_id,
        query=body.query,
        answer=answer,
        latency_ms=round(latency_ms, 2),
    )


# ──────────────────────────────────────────────
# Entry Point
# ──────────────────────────────────────────────

if __name__ == "__main__":
    """
    Run the API server directly via Uvicorn.

    Requires a built FAISS index and valid API keys in config/config.py.

    Run from the project root:
        uv run python src/api/main.py

    Or with hot-reload for development:
        uv run uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    """
    uvicorn.run(
        "main:app",
        host=API_HOST,
        port=API_PORT,
        reload=False,
        log_level="info",
    )
